language: node_js
node_js:
- 10.16.0
branchs:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
install:
- yarn
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh ubuntu@13.112.54.35 -o StrictHostKeyChecking=no 'cd ~/usr/app/umbra && git pull && yarn && yarn start'
script: true
