version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:10.16.0-alpine
    container_name: umbra
    restart: unless-stopped
    # env_file: .env
    # environment:
    #   - MONGO_USERNAME=$MONGO_USERNAME
    #   - MONGO_PASSWORD=$MONGO_PASSWORD
    #   - MONGO_HOSTNAME=db
    #   - MONGO_PORT=$MONGO_PORT
    #   - MONGO_DB=$MONGO_DB
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: yarn start

  db:
    image: mongo:4.0.10-xenial
    container_name: db
    restart: unless-stopped
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: